global_coordinates:
  altitude: 90.0
  latitude: 38.736832
  longitude: -9.137977
px4_dir: ~/PX4-Autopilot
px4_default_airframe: gazebo-classic_iris # Change to 'iris' if using PX4 version lower than v1.14